services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    markenzoo_expo_push_notification.expo_push_notification_controller:
        class: Markenzoo\ContaoExpoPushNotificationBundle\Controller\ExpoPushNotificationController
        tags: ['controller.service_arguments']

    markenzoo_expo_push_notification.expo_push_token_repository:
        class: Markenzoo\ContaoExpoPushNotificationBundle\Repository\ExpoPushTokenRepository
        tags: ['doctrine.repository_service']
        arguments:
            - '@doctrine'

    sc_expo_notifications.guzzle_client:
       class: GuzzleHttp\Client
       arguments: []
       public: true

    sc_expo_notifications.notification_manager:
       class: Solvecrew\ExpoNotificationsBundle\Manager\NotificationManager
       arguments: ['doctrine.orm.default_entity_manager', '@sc_expo_notifications.guzzle_client', 'https://exp.host/--/api/v2/push/send']
       public: true
